name: Bad CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd lab3
          mkdir build
          cp main.py build/main.py

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: |
          cd lab3
          python -m pip install --upgrade pip
          pip install pytest
      - run: |
          cd lab3
          pytest test_main.py

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd lab3
          scp build/main.py user@production:/app/main.py
