name: Good CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build project
        run: |
          cd lab3
          mkdir build
          cp main.py build/main.py

  test:
    runs-on: ubuntu-22.04
    needs: build
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'
      - name: Install dependencies
        run: |
          cd lab3
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: |
          cd lab3
          pytest test_main.py
